# Generated by Django 5.0.6 on 2024-05-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField()),
                ('totalOrders', models.IntegerField()),
                ('completedOrders', models.IntegerField()),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ratio', models.CharField(max_length=10)),
                ('completedTime', models.TimeField()),
            ],
        ),
    ]
